[phases.setup]
nixPkgs = ['nodejs', 'yarn']

[phases.install]
cmds = ['yarn install']

[phases.build]
cmds = [
  'yarn nx run devswhorun-api:build:production',
]

[start]
cmd = 'node dist/backend/devswhorun-api/main.js'