name: 'build and test'
description: 'build and run tests for all projects'
runs:
  using: 'composite'
  steps:
    - name: run format check
      shell: bash
      run: yarn nx format:check
    - name: run affected lint, test, and build
      shell: bash
      run: yarn nx affected -t lint test build
