name: 'build and test'
description: 'build and run tests for all projects'
runs:
  using: 'composite'
  steps:
    - name: run format check
      run: npx nx format:check
    - name: run affected lint, test, and build
      run: npx nx affected -t lint test build
